// Study plans for the grade calculators. GENERATED by
// bocconi-scraper/grade-plans/gen_plans.py : edit that, not this file.
// Bachelor: Bocconi's 2025-26 study-plan guide. MSc and CLMG: the course lists
// B.lab Bocconi publishes for its calculators.
//
// Row: n = course name ("#N" = the Nth optional slot, named in the app's
// language), c = credits, y = year, m = parent course when it is one module of
// an integrated exam, k = kind:
//   g graded course · p pass/fail seminar (no grade, not in the average)
//   o optional course · s optional that an internship can replace
//   i internship (no grade) that an optional course can replace

export type PlanKind = "g" | "p" | "o" | "s" | "i";
export interface PlanRow {
  n: string;
  c: number;
  y: number;
  k: PlanKind;
  m?: string;
}

export const GRADE_PLANS: {
  bachelor: Record<string, PlanRow[]>;
  master: Record<string, PlanRow[]>;
  clmg: Record<string, PlanRow[]>;
} = {
 "bachelor": {
  "CLEAM": [
   {
    "n": "Economia aziendale e gestione delle imprese",
    "c": 10,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Economia - Modulo 1 (Microeconomia)",
    "c": 9,
    "y": 1,
    "k": "g",
    "m": "Economia"
   },
   {
    "n": "Matematica - Modulo 1 (Generale)",
    "c": 8,
    "y": 1,
    "k": "g",
    "m": "Matematica"
   },
   {
    "n": "Seminario di Critical thinking",
    "c": 1,
    "y": 1,
    "k": "p"
   },
   {
    "n": "Economia - Modulo 2 (Macroeconomia)",
    "c": 8,
    "y": 1,
    "k": "g",
    "m": "Economia"
   },
   {
    "n": "Matematica - Modulo 2 (Applicata)",
    "c": 7,
    "y": 1,
    "k": "g",
    "m": "Matematica"
   },
   {
    "n": "Diritto - Modulo 1 (Privato)",
    "c": 6,
    "y": 1,
    "k": "g",
    "m": "Diritto"
   },
   {
    "n": "Computer science",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Inglese (I lingua)",
    "c": 4,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Bilancio - Modulo 1",
    "c": 5,
    "y": 2,
    "k": "g",
    "m": "Bilancio"
   },
   {
    "n": "Storia economica",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Sistema finanziario",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Statistica",
    "c": 8,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Diritto - Modulo 2 (Pubblico Comparato)",
    "c": 6,
    "y": 2,
    "k": "g",
    "m": "Diritto"
   },
   {
    "n": "Bilancio - Modulo 2",
    "c": 5,
    "y": 2,
    "k": "g",
    "m": "Bilancio"
   },
   {
    "n": "Economia e management delle amministrazioni pubbliche",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Marketing",
    "c": 7,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Programmazione e controllo",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Seminari di Business Ethics e responsabilità sociale",
    "c": 1,
    "y": 2,
    "k": "p"
   },
   {
    "n": "Seconda lingua",
    "c": 4,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Finanza aziendale",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Fondamenti di organizzazione",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Strategia e innovazione - Modulo 1 (Strategia competitiva)",
    "c": 7,
    "y": 3,
    "k": "g",
    "m": "Strategia e innovazione"
   },
   {
    "n": "Strategia e innovazione - Modulo 2 (Gestione della tecnologia, dell'innovazione e delle operations)",
    "c": 7,
    "y": 3,
    "k": "g",
    "m": "Strategia e innovazione"
   },
   {
    "n": "Seminari per lo sviluppo delle competenze manageriali e di leadership",
    "c": 1,
    "y": 3,
    "k": "p"
   },
   {
    "n": "#1",
    "c": 6,
    "y": 3,
    "k": "o"
   },
   {
    "n": "Diritto commerciale",
    "c": 7,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Scienza delle finanze",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "#2",
    "c": 6,
    "y": 3,
    "k": "o"
   },
   {
    "n": "#3",
    "c": 6,
    "y": 3,
    "k": "s"
   }
  ],
  "CLEF": [
   {
    "n": "Economia aziendale e gestione delle imprese",
    "c": 10,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Economia - Modulo 1 (Microeconomia)",
    "c": 9,
    "y": 1,
    "k": "g",
    "m": "Economia"
   },
   {
    "n": "Matematica - Modulo 1 (Generale)",
    "c": 8,
    "y": 1,
    "k": "g",
    "m": "Matematica"
   },
   {
    "n": "Seminario di Critical thinking",
    "c": 1,
    "y": 1,
    "k": "p"
   },
   {
    "n": "Economia - Modulo 2 (Macroeconomia)",
    "c": 8,
    "y": 1,
    "k": "g",
    "m": "Economia"
   },
   {
    "n": "Matematica - Modulo 2 (Applicata)",
    "c": 7,
    "y": 1,
    "k": "g",
    "m": "Matematica"
   },
   {
    "n": "Diritto - Modulo 1 (Privato)",
    "c": 6,
    "y": 1,
    "k": "g",
    "m": "Diritto"
   },
   {
    "n": "Computer science",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Inglese (I lingua)",
    "c": 4,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Bilancio - Modulo 1",
    "c": 5,
    "y": 2,
    "k": "g",
    "m": "Bilancio"
   },
   {
    "n": "Storia economica",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Sistema finanziario",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Statistica",
    "c": 8,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Diritto - Modulo 2 (Pubblico)",
    "c": 6,
    "y": 2,
    "k": "g",
    "m": "Diritto"
   },
   {
    "n": "Scienza delle finanze",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Bilancio - Modulo 2",
    "c": 5,
    "y": 2,
    "k": "g",
    "m": "Bilancio"
   },
   {
    "n": "Investimenti finanziari",
    "c": 8,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Metodi quantitativi per la finanza",
    "c": 8,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Seminari per lo sviluppo delle competenze manageriali e di leadership",
    "c": 1,
    "y": 2,
    "k": "p"
   },
   {
    "n": "Seconda lingua",
    "c": 4,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Monetary economics",
    "c": 8,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Corporate finance",
    "c": 8,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Financial statement analysis",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "#1",
    "c": 6,
    "y": 3,
    "k": "o"
   },
   {
    "n": "Diritto commerciale",
    "c": 7,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Economia e gestione delle istituzioni finanziarie",
    "c": 8,
    "y": 3,
    "k": "g"
   },
   {
    "n": "#2",
    "c": 6,
    "y": 3,
    "k": "o"
   },
   {
    "n": "#3",
    "c": 6,
    "y": 3,
    "k": "s"
   }
  ],
  "BESS": [
   {
    "n": "Mathematics - Module 1 (Theory and methods)",
    "c": 9,
    "y": 1,
    "k": "g",
    "m": "Mathematics"
   },
   {
    "n": "Fundamentals of management",
    "c": 7,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Foundations of economics - Module 1 (Microeconomics)",
    "c": 7,
    "y": 1,
    "k": "g",
    "m": "Foundations of economics"
   },
   {
    "n": "Logic and methodology of social sciences",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Mathematics - Module 2 (Applied mathematics)",
    "c": 9,
    "y": 1,
    "k": "g",
    "m": "Mathematics"
   },
   {
    "n": "Foundations of economics - Module 2 (Macroeconomics)",
    "c": 7,
    "y": 1,
    "k": "g",
    "m": "Foundations of economics"
   },
   {
    "n": "Statistics - Module 1 (Theory and methods)",
    "c": 7,
    "y": 1,
    "k": "g",
    "m": "Statistics"
   },
   {
    "n": "Computer science",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Prima lingua",
    "c": 4,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Statistics - Module 2 (Applied statistics)",
    "c": 7,
    "y": 2,
    "k": "g",
    "m": "Statistics"
   },
   {
    "n": "Strategic decision making and markets",
    "c": 8,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Macroeconomics and economic policy",
    "c": 8,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Economic history",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Incentives design and policy",
    "c": 7,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Private and business law",
    "c": 8,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Econometrics",
    "c": 7,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Social Sciences 1 (Cognitive sciences)",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Seconda lingua",
    "c": 4,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Empirical research methods and data analysis",
    "c": 7,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Social Sciences 2 - Module 1 (Organizational behavior and social psychology)",
    "c": 8,
    "y": 3,
    "k": "g",
    "m": "Social Sciences 2"
   },
   {
    "n": "Law and public policy",
    "c": 7,
    "y": 3,
    "k": "g"
   },
   {
    "n": "#1",
    "c": 6,
    "y": 3,
    "k": "o"
   },
   {
    "n": "Culture, institutions and development",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Social Sciences 2 - Module 2 (Sociology)",
    "c": 7,
    "y": 3,
    "k": "g",
    "m": "Social Sciences 2"
   },
   {
    "n": "International economics and finance",
    "c": 7,
    "y": 3,
    "k": "g"
   },
   {
    "n": "#2",
    "c": 6,
    "y": 3,
    "k": "s"
   }
  ],
  "BEMACS": [
   {
    "n": "Mathematics and statistics - Module 1 (Mathematics)",
    "c": 8,
    "y": 1,
    "k": "g",
    "m": "Mathematics and statistics"
   },
   {
    "n": "Fundamentals of computer science",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Microeconomics",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Principles of Management",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Mathematics and statistics - Module 2 (Statistics)",
    "c": 8,
    "y": 1,
    "k": "g",
    "m": "Mathematics and statistics"
   },
   {
    "n": "Accounting",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Fundamentals of information technology law",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Prima lingua",
    "c": 4,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Advanced mathematics and statistics - Module 1 (Applied mathematics)",
    "c": 7,
    "y": 2,
    "k": "g",
    "m": "Advanced mathematics and statistics"
   },
   {
    "n": "Advanced mathematics and statistics - Module 2 (Advanced statistical methods)",
    "c": 7,
    "y": 2,
    "k": "g",
    "m": "Advanced mathematics and statistics"
   },
   {
    "n": "Macroeconomics",
    "c": 8,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Computer programming",
    "c": 7,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Technological innovation seminars I",
    "c": 1,
    "y": 2,
    "k": "p"
   },
   {
    "n": "European IP and data law",
    "c": 7,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Machine learning",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Econometrics",
    "c": 8,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Principles of finance",
    "c": 7,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Technological innovation seminars II",
    "c": 1,
    "y": 2,
    "k": "p"
   },
   {
    "n": "Seconda lingua",
    "c": 4,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Big data and databases",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Computational microeconomics - Module 1 (Game theory)",
    "c": 8,
    "y": 3,
    "k": "g",
    "m": "Computational microeconomics"
   },
   {
    "n": "Marketing analytics",
    "c": 8,
    "y": 3,
    "k": "g"
   },
   {
    "n": "#1",
    "c": 6,
    "y": 3,
    "k": "o"
   },
   {
    "n": "Computational microeconomics - Module 2 (Mechanism design)",
    "c": 8,
    "y": 3,
    "k": "g",
    "m": "Computational microeconomics"
   },
   {
    "n": "Information systems management",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "#2",
    "c": 6,
    "y": 3,
    "k": "s"
   },
   {
    "n": "#3",
    "c": 6,
    "y": 3,
    "k": "s"
   }
  ],
  "BIEM": [
   {
    "n": "Economics - Module 1 (Microeconomics)",
    "c": 9,
    "y": 1,
    "k": "g",
    "m": "Economics"
   },
   {
    "n": "Management",
    "c": 10,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Mathematics - Module 1 (General)",
    "c": 8,
    "y": 1,
    "k": "g",
    "m": "Mathematics"
   },
   {
    "n": "Critical thinking seminar",
    "c": 1,
    "y": 1,
    "k": "p"
   },
   {
    "n": "Introduction to the legal system - Module 1",
    "c": 6,
    "y": 1,
    "k": "g",
    "m": "Introduction to the legal system"
   },
   {
    "n": "Economics - Module 2 (Macroeconomics)",
    "c": 8,
    "y": 1,
    "k": "g",
    "m": "Economics"
   },
   {
    "n": "Mathematics - Module 2 (Applied)",
    "c": 7,
    "y": 1,
    "k": "g",
    "m": "Mathematics"
   },
   {
    "n": "Computer science",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Prima lingua",
    "c": 4,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Financial accounting - Module 1",
    "c": 5,
    "y": 2,
    "k": "g",
    "m": "Financial accounting"
   },
   {
    "n": "Finance - Module 1 (Financial markets and institutions)",
    "c": 6,
    "y": 2,
    "k": "g",
    "m": "Finance"
   },
   {
    "n": "Statistics",
    "c": 8,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Economic history",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Introduction to the legal system - Module 2",
    "c": 6,
    "y": 2,
    "k": "g",
    "m": "Introduction to the legal system"
   },
   {
    "n": "Financial accounting - Module 2",
    "c": 5,
    "y": 2,
    "k": "g",
    "m": "Financial accounting"
   },
   {
    "n": "Finance - Module 2 (Corporate finance)",
    "c": 6,
    "y": 2,
    "k": "g",
    "m": "Finance"
   },
   {
    "n": "Marketing",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "1 corso a scelta tra European economic policy / Public finance",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Leadership and managerial skills seminar",
    "c": 1,
    "y": 2,
    "k": "p"
   },
   {
    "n": "Seconda lingua",
    "c": 4,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Applications for management",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "International macroeconomics",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Insegnamento obbligatorio di percorso 1 of 3",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Insegnamento obbligatorio di percorso 2 of 3",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Insegnamento obbligatorio di percorso 3 of 3",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "CSR & Ethics in Business (seminar)",
    "c": 2,
    "y": 3,
    "k": "p"
   },
   {
    "n": "Business strategy",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Comparative business and European law",
    "c": 7,
    "y": 3,
    "k": "g"
   },
   {
    "n": "#1",
    "c": 6,
    "y": 3,
    "k": "o"
   },
   {
    "n": "#2",
    "c": 6,
    "y": 3,
    "k": "s"
   },
   {
    "n": "Globalization, societies and institutions (seminar)",
    "c": 2,
    "y": 3,
    "k": "p"
   }
  ],
  "BIEF-ECON": [
   {
    "n": "Economics - Module 1 (Microeconomics)",
    "c": 9,
    "y": 1,
    "k": "g",
    "m": "Economics"
   },
   {
    "n": "Management",
    "c": 10,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Mathematics - Module 1 (General)",
    "c": 8,
    "y": 1,
    "k": "g",
    "m": "Mathematics"
   },
   {
    "n": "Critical thinking seminar",
    "c": 1,
    "y": 1,
    "k": "p"
   },
   {
    "n": "Introduction to the legal system - Module 1",
    "c": 6,
    "y": 1,
    "k": "g",
    "m": "Introduction to the legal system"
   },
   {
    "n": "Economics - Module 2 (Macroeconomics)",
    "c": 8,
    "y": 1,
    "k": "g",
    "m": "Economics"
   },
   {
    "n": "Mathematics - Module 2 (Applied)",
    "c": 7,
    "y": 1,
    "k": "g",
    "m": "Mathematics"
   },
   {
    "n": "Computer science",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Prima lingua",
    "c": 4,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Financial accounting - Module 1",
    "c": 5,
    "y": 2,
    "k": "g",
    "m": "Financial accounting"
   },
   {
    "n": "Finance - Module 1 (Financial markets and institutions)",
    "c": 6,
    "y": 2,
    "k": "g",
    "m": "Finance"
   },
   {
    "n": "Economic history",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Statistics",
    "c": 8,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Introduction to the legal system - Module 2",
    "c": 6,
    "y": 2,
    "k": "g",
    "m": "Introduction to the legal system"
   },
   {
    "n": "Leadership and managerial skills seminar",
    "c": 1,
    "y": 2,
    "k": "p"
   },
   {
    "n": "Finance - Module 2 (Corporate finance)",
    "c": 6,
    "y": 2,
    "k": "g",
    "m": "Finance"
   },
   {
    "n": "Financial accounting - Module 2",
    "c": 5,
    "y": 2,
    "k": "g",
    "m": "Financial accounting"
   },
   {
    "n": "Seconda lingua",
    "c": 4,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Markets, Organization and Incentives",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "International economics",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "CSR & Ethics in Business (seminar)",
    "c": 2,
    "y": 3,
    "k": "p"
   },
   {
    "n": "Comparative business and European law",
    "c": 7,
    "y": 3,
    "k": "g"
   },
   {
    "n": "#1",
    "c": 6,
    "y": 3,
    "k": "o"
   },
   {
    "n": "#2",
    "c": 6,
    "y": 3,
    "k": "s"
   },
   {
    "n": "Globalization, societies and institutions (seminar)",
    "c": 2,
    "y": 3,
    "k": "p"
   },
   {
    "n": "Empirical methods for economics (Introduction to econometrics)",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Macroeconomics and the world economy",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Major course 1",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Major course 2",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Major course 3",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Major course 4",
    "c": 6,
    "y": 3,
    "k": "g"
   }
  ],
  "BIEF-FIN": [
   {
    "n": "Economics - Module 1 (Microeconomics)",
    "c": 9,
    "y": 1,
    "k": "g",
    "m": "Economics"
   },
   {
    "n": "Management",
    "c": 10,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Mathematics - Module 1 (General)",
    "c": 8,
    "y": 1,
    "k": "g",
    "m": "Mathematics"
   },
   {
    "n": "Critical thinking seminar",
    "c": 1,
    "y": 1,
    "k": "p"
   },
   {
    "n": "Introduction to the legal system - Module 1",
    "c": 6,
    "y": 1,
    "k": "g",
    "m": "Introduction to the legal system"
   },
   {
    "n": "Economics - Module 2 (Macroeconomics)",
    "c": 8,
    "y": 1,
    "k": "g",
    "m": "Economics"
   },
   {
    "n": "Mathematics - Module 2 (Applied)",
    "c": 7,
    "y": 1,
    "k": "g",
    "m": "Mathematics"
   },
   {
    "n": "Computer science",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Prima lingua",
    "c": 4,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Financial accounting - Module 1",
    "c": 5,
    "y": 2,
    "k": "g",
    "m": "Financial accounting"
   },
   {
    "n": "Finance - Module 1 (Financial markets and institutions)",
    "c": 6,
    "y": 2,
    "k": "g",
    "m": "Finance"
   },
   {
    "n": "Economic history",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Statistics",
    "c": 8,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Introduction to the legal system - Module 2",
    "c": 6,
    "y": 2,
    "k": "g",
    "m": "Introduction to the legal system"
   },
   {
    "n": "Leadership and managerial skills seminar",
    "c": 1,
    "y": 2,
    "k": "p"
   },
   {
    "n": "Finance - Module 2 (Corporate finance)",
    "c": 6,
    "y": 2,
    "k": "g",
    "m": "Finance"
   },
   {
    "n": "Financial accounting - Module 2",
    "c": 5,
    "y": 2,
    "k": "g",
    "m": "Financial accounting"
   },
   {
    "n": "Seconda lingua",
    "c": 4,
    "y": 2,
    "k": "g"
   },
   {
    "n": "International and monetary economics",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Financial economics",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "CSR & Ethics in Business (seminar)",
    "c": 2,
    "y": 3,
    "k": "p"
   },
   {
    "n": "Comparative business and European law",
    "c": 7,
    "y": 3,
    "k": "g"
   },
   {
    "n": "#1",
    "c": 6,
    "y": 3,
    "k": "o"
   },
   {
    "n": "#2",
    "c": 6,
    "y": 3,
    "k": "s"
   },
   {
    "n": "Globalization, societies and institutions (seminar)",
    "c": 2,
    "y": 3,
    "k": "p"
   },
   {
    "n": "Empirical methods for finance (Introduction to econometrics for finance)",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Business strategy",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Major course 1",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Major course 2",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Major course 3",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Major course 4",
    "c": 6,
    "y": 3,
    "k": "g"
   }
  ],
  "CLEACC-ENG": [
   {
    "n": "Management of cultural companies and institutions",
    "c": 10,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Philosophy of art",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Mathematics",
    "c": 9,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Law - Module 1 (Private law)",
    "c": 6,
    "y": 1,
    "k": "g",
    "m": "Law"
   },
   {
    "n": "Economics - Module 1 (Microeconomics)",
    "c": 7,
    "y": 1,
    "k": "g",
    "m": "Economics"
   },
   {
    "n": "Economic history and history of economic thought",
    "c": 7,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Critical approaches to the arts",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Computer science",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Prima lingua",
    "c": 4,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Economics - Module 2 (Macroeconomics)",
    "c": 7,
    "y": 2,
    "k": "g",
    "m": "Economics"
   },
   {
    "n": "Statistics",
    "c": 8,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Critical approaches to the arts II - Module 1 (un insegnamento di percorso a scelta)",
    "c": 6,
    "y": 2,
    "k": "g",
    "m": "Metodo, critica e ricerca nelle discipline artistiche II"
   },
   {
    "n": "Financial accounting - Module 1",
    "c": 5,
    "y": 2,
    "k": "g",
    "m": "Financial accounting"
   },
   {
    "n": "Cultural anthropology",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Financial accounting - Module 2",
    "c": 5,
    "y": 2,
    "k": "g",
    "m": "Financial accounting"
   },
   {
    "n": "Foundamentals of organization",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Critical approaches to the arts II - Module 2 (un insegnamento di percorso a scelta)",
    "c": 6,
    "y": 2,
    "k": "g",
    "m": "Metodo, critica e ricerca nelle discipline artistiche II"
   },
   {
    "n": "Law - Module 2 (Comparative Public law)",
    "c": 6,
    "y": 2,
    "k": "g",
    "m": "Law"
   },
   {
    "n": "Leadership and managerial skills seminar",
    "c": 2,
    "y": 2,
    "k": "p"
   },
   {
    "n": "Seconda lingua",
    "c": 4,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Business planning and control",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Advanced Management - Modulo 1 (Competitive strategies in creative industries)",
    "c": 7,
    "y": 3,
    "k": "g",
    "m": "Advanced Management"
   },
   {
    "n": "Advanced Management - Modulo 2 (Marketing in creative industries)",
    "c": 8,
    "y": 3,
    "k": "g",
    "m": "Advanced Management"
   },
   {
    "n": "Management of public and not for profit organizations",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Company and business law",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Laboratorio / opzionale all'estero",
    "c": 6,
    "y": 3,
    "k": "s"
   },
   {
    "n": "Public finance",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Finance - Module 1 (Corporate finance)",
    "c": 5,
    "y": 3,
    "k": "g",
    "m": "Finance"
   },
   {
    "n": "Finance - Module 2 (Financial markets and institutions)",
    "c": 5,
    "y": 3,
    "k": "g",
    "m": "Finance"
   }
  ],
  "CLEACC": [
   {
    "n": "Economia aziendale e delle istituzioni culturali",
    "c": 10,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Estetica",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Matematica generale e finanziaria",
    "c": 9,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Diritto - Modulo 1 (Privato)",
    "c": 6,
    "y": 1,
    "k": "g",
    "m": "Diritto"
   },
   {
    "n": "Economia - Modulo 1 (Microeconomia)",
    "c": 7,
    "y": 1,
    "k": "g",
    "m": "Economia"
   },
   {
    "n": "Storia economica e del pensiero economico",
    "c": 7,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Metodo, critica e ricerca nelle discipline artistiche",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Computer science",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Inglese (I lingua)",
    "c": 4,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Economia - Modulo 2 (Macroeconomia)",
    "c": 7,
    "y": 2,
    "k": "g",
    "m": "Economia"
   },
   {
    "n": "Statistica",
    "c": 8,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Metodo, critica e ricerca nelle discipline artistiche II - Modulo 1 (un insegnamento di percorso a scelta)",
    "c": 6,
    "y": 2,
    "k": "g",
    "m": "Metodo, critica e ricerca nelle discipline artistiche II"
   },
   {
    "n": "Bilancio - Modulo 1",
    "c": 5,
    "y": 2,
    "k": "g",
    "m": "Bilancio"
   },
   {
    "n": "Antropologia culturale e dello sviluppo",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Bilancio - Modulo 2",
    "c": 5,
    "y": 2,
    "k": "g",
    "m": "Bilancio"
   },
   {
    "n": "Fondamenti di organizzazione",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Metodo, critica e ricerca nelle discipline artistiche II - Modulo 2 (un insegnamento di percorso a scelta)",
    "c": 6,
    "y": 2,
    "k": "g",
    "m": "Metodo, critica e ricerca nelle discipline artistiche II"
   },
   {
    "n": "Diritto - Modulo 2 (Pubblico Comparato)",
    "c": 6,
    "y": 2,
    "k": "g",
    "m": "Diritto"
   },
   {
    "n": "Seminari per lo sviluppo delle competenze manageriali e di leadership",
    "c": 2,
    "y": 2,
    "k": "p"
   },
   {
    "n": "Seconda lingua",
    "c": 4,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Programmazione e controllo",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Advanced Management - Modulo 1 (Competitive strategies in creative industries)",
    "c": 7,
    "y": 3,
    "k": "g",
    "m": "Advanced Management"
   },
   {
    "n": "Advanced Management - Modulo 2 (Marketing nei settori creativi)",
    "c": 8,
    "y": 3,
    "k": "g",
    "m": "Advanced Management"
   },
   {
    "n": "Management of public and not for profit organizations",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Diritto commerciale",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Laboratorio / opzionale all'estero",
    "c": 6,
    "y": 3,
    "k": "s"
   },
   {
    "n": "Scienza delle finanze",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Finanza - Modulo 1 (Finanza aziendale)",
    "c": 5,
    "y": 3,
    "k": "g",
    "m": "Finanza"
   },
   {
    "n": "Finanza - Modulo 2 (Sistema finanziario)",
    "c": 5,
    "y": 3,
    "k": "g",
    "m": "Finanza"
   }
  ],
  "BIG-DSO": [
   {
    "n": "Economics (Module I - Consumer behavior & firms)",
    "c": 6,
    "y": 1,
    "k": "g",
    "m": "Economics"
   },
   {
    "n": "Comparative public law and regulation",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Politics & public sector",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Quantitative methods for social sciences (Module I - Mathematics for social sciences)",
    "c": 6,
    "y": 1,
    "k": "g",
    "m": "Quantitative methods for social sciences"
   },
   {
    "n": "Coding and data visualization in Python",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Economics (Module II - Macro-economic governance)",
    "c": 6,
    "y": 1,
    "k": "g",
    "m": "Economics"
   },
   {
    "n": "Global history and affairs",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Machine learning (Module I - Introduction)",
    "c": 5,
    "y": 1,
    "k": "g",
    "m": "Machine learning"
   },
   {
    "n": "Quantitative methods for social sciences (Module II - Data analytics)",
    "c": 6,
    "y": 1,
    "k": "g",
    "m": "Quantitative methods for social sciences"
   },
   {
    "n": "Prima lingua",
    "c": 5,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Governance of digital technologies in public & private sector",
    "c": 7,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Social transformations",
    "c": 8,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Social media & democracy",
    "c": 8,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Machine learning (Module II - Deep learning)",
    "c": 8,
    "y": 2,
    "k": "g",
    "m": "Machine learning"
   },
   {
    "n": "Climate change and sustainability (HEC)",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Business analytics & Data modelling (HEC)",
    "c": 8,
    "y": 2,
    "k": "g"
   },
   {
    "n": "European governance (HEC)",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Behavioral and cognitive science (HEC)",
    "c": 8,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Introduction to ethics and philosophy of AI and technology (seminar) (HEC)",
    "c": 2,
    "y": 2,
    "k": "p"
   },
   {
    "n": "Seconda lingua",
    "c": 5,
    "y": 2,
    "k": "g"
   },
   {
    "n": "#1",
    "c": 6,
    "y": 3,
    "k": "s"
   },
   {
    "n": "Introduction to research methods (seminario)",
    "c": 3,
    "y": 3,
    "k": "p"
   },
   {
    "n": "Entrepreneurial management methods for addressing challenges (seminario)",
    "c": 3,
    "y": 3,
    "k": "p"
   },
   {
    "n": "#2",
    "c": 3,
    "y": 3,
    "k": "o"
   },
   {
    "n": "#3",
    "c": 3,
    "y": 3,
    "k": "o"
   },
   {
    "n": "#4",
    "c": 3,
    "y": 3,
    "k": "o"
   },
   {
    "n": "#5",
    "c": 3,
    "y": 3,
    "k": "o"
   },
   {
    "n": "#6",
    "c": 3,
    "y": 3,
    "k": "o"
   },
   {
    "n": "#7",
    "c": 3,
    "y": 3,
    "k": "o"
   },
   {
    "n": "Capstone project",
    "c": 15,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Progetto sul campo/Laboratori",
    "c": 6,
    "y": 3,
    "k": "g"
   }
  ],
  "BAI": [
   {
    "n": "Foundations of Economic Sciences",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Computer Science - Module 1 (Introduction to Computer Science and Programming)",
    "c": 8,
    "y": 1,
    "k": "g",
    "m": "Computer Science"
   },
   {
    "n": "Mathematical Analysis I - Module 1",
    "c": 8,
    "y": 1,
    "k": "g",
    "m": "Mathematical Analysis I"
   },
   {
    "n": "Algebra and Geometry",
    "c": 7,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Foundations of Physics I",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Computer Science - Module 2 (Computing Theory and Algorithms)",
    "c": 8,
    "y": 1,
    "k": "g",
    "m": "Computer Science"
   },
   {
    "n": "Probability",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Mathematical Analysis I - Module 2",
    "c": 7,
    "y": 1,
    "k": "g",
    "m": "Mathematical Analysis I"
   },
   {
    "n": "Foundations of Physics II",
    "c": 8,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Decision Theory and Human Behaviour",
    "c": 8,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Mathematical Statistics",
    "c": 8,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Mathematical Analysis II - Module 1",
    "c": 5,
    "y": 2,
    "k": "g",
    "m": "Mathematical Analysis II"
   },
   {
    "n": "Advanced Programming and Optimization Algorithms",
    "c": 8,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Mathematical Modelling in Machine Learning",
    "c": 8,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Mathematical Analysis II - Module 2",
    "c": 5,
    "y": 2,
    "k": "g",
    "m": "Mathematical Analysis II"
   },
   {
    "n": "Digital Ethics seminar",
    "c": 1,
    "y": 2,
    "k": "p"
   },
   {
    "n": "Behavioural skills seminar",
    "c": 1,
    "y": 2,
    "k": "p"
   },
   {
    "n": "AI Lab",
    "c": 1,
    "y": 2,
    "k": "p"
   },
   {
    "n": "Lingua",
    "c": 4,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Game Theory and Mechanism Design",
    "c": 8,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Mathematical Modelling for Finance",
    "c": 8,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Stochastic Processes and Simulation in Natural Sciences",
    "c": 8,
    "y": 3,
    "k": "g"
   },
   {
    "n": "#1",
    "c": 6,
    "y": 3,
    "k": "s"
   },
   {
    "n": "Statistical and Quantum Physics",
    "c": 8,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Machine Learning and Artificial Intelligence",
    "c": 8,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Mathematical Modelling for Neuroscience",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "#2",
    "c": 6,
    "y": 3,
    "k": "o"
   }
  ],
  "BGL-GL": [
   {
    "n": "General Jurisprudence",
    "c": 9,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Critical thinking seminar",
    "c": 1,
    "y": 1,
    "k": "p"
   },
   {
    "n": "Introduction to Private Law - Module 1 (Civil Law)",
    "c": 9,
    "y": 1,
    "k": "g",
    "m": "Introduction to Private Law"
   },
   {
    "n": "Introduction to Private Law - Module 2 (Common Law)",
    "c": 9,
    "y": 1,
    "k": "g",
    "m": "Introduction to Private Law"
   },
   {
    "n": "Transnational Constitutional Law - Module 1 (European Legal Systems)",
    "c": 10,
    "y": 1,
    "k": "g",
    "m": "Transnational Constitutional Law"
   },
   {
    "n": "Transnational Constitutional Law - Module 2 (Anglo-American Legal Systems)",
    "c": 8,
    "y": 1,
    "k": "g",
    "m": "Transnational Constitutional Law"
   },
   {
    "n": "Historical Foundations of Law - Module 1 (Civil law)",
    "c": 6,
    "y": 1,
    "k": "g",
    "m": "Historical Foundations of Law"
   },
   {
    "n": "Historical Foundations of Law - Module 2 (Common law)",
    "c": 6,
    "y": 1,
    "k": "g",
    "m": "Historical Foundations of Law"
   },
   {
    "n": "European Union law",
    "c": 9,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Management of International Organizations",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Labour and Social Law",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "International law",
    "c": 9,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Legal Tech",
    "c": 3,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Global administrative law",
    "c": 8,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Microeconomics oppure Public Finance",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Criminal Law",
    "c": 10,
    "y": 2,
    "k": "g"
   },
   {
    "n": "EU language",
    "c": 4,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Quantitative analysis for global jurists",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Business and Corporate Law",
    "c": 10,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Global Civil Justice oppure Criminal Procedure",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Economic Analysis of law oppure International Political Affairs",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Administrative environmental law and climate change oppure Gender Law and women's rights",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Regulatory law oppure Global Finance",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Fundamentals of IT and IP Law oppure Sports law",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Legal clinic oppure Internship",
    "c": 6,
    "y": 3,
    "k": "i"
   },
   {
    "n": "Due seminari tra: Cultural aspects of international negotiations / Democracy lab / Global diplomacy",
    "c": 6,
    "y": 3,
    "k": "p"
   }
  ],
  "BGL-DL": [
   {
    "n": "General Jurisprudence",
    "c": 9,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Critical thinking seminar",
    "c": 1,
    "y": 1,
    "k": "p"
   },
   {
    "n": "Introduction to Private Law - Module 1 (Civil Law)",
    "c": 9,
    "y": 1,
    "k": "g",
    "m": "Introduction to Private Law"
   },
   {
    "n": "Introduction to Private Law - Module 2 (Common Law)",
    "c": 9,
    "y": 1,
    "k": "g",
    "m": "Introduction to Private Law"
   },
   {
    "n": "Transnational Constitutional Law - Module 1 (European Legal Systems)",
    "c": 10,
    "y": 1,
    "k": "g",
    "m": "Transnational Constitutional Law"
   },
   {
    "n": "Transnational Constitutional Law - Module 2 (Anglo-American Legal Systems)",
    "c": 8,
    "y": 1,
    "k": "g",
    "m": "Transnational Constitutional Law"
   },
   {
    "n": "Historical Foundations of Law - Module 1 (Civil law)",
    "c": 6,
    "y": 1,
    "k": "g",
    "m": "Historical Foundations of Law"
   },
   {
    "n": "Historical Foundations of Law - Module 2 (Common law)",
    "c": 6,
    "y": 1,
    "k": "g",
    "m": "Historical Foundations of Law"
   },
   {
    "n": "European Union law",
    "c": 9,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Management of International Organizations",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Labour and Social Law",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "International law",
    "c": 9,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Legal Tech",
    "c": 3,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Global administrative law",
    "c": 8,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Microeconomics oppure Public Finance",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Criminal Law",
    "c": 10,
    "y": 2,
    "k": "g"
   },
   {
    "n": "EU language",
    "c": 4,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Quantitative analysis for global jurists",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Business and Corporate Law",
    "c": 10,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Criminal Procedure",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Disciplina giuridica di bilancio",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "1 insegnamento a scelta tra Casi e questioni di diritto societario / Operazioni straordinarie",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Regulatory law oppure Global Finance",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Accounting and financial statement analysis",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Diritto Privato",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Diritto tributario",
    "c": 6,
    "y": 3,
    "k": "g"
   }
  ],
  "BEMACC": [
   {
    "n": "Management of Cultural Companies and Institutions",
    "c": 10,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Mathematics",
    "c": 9,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Philosophy of Art",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Law - Module 1 (Private Law)",
    "c": 6,
    "y": 1,
    "k": "g",
    "m": "LAW"
   },
   {
    "n": "Economics - Module 1 (Microeconomics)",
    "c": 7,
    "y": 1,
    "k": "g",
    "m": "ECONOMICS"
   },
   {
    "n": "Critical Approaches to the Arts - I",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Economic History and History of Economic Thought",
    "c": 7,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Computer Science",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "First foreign language",
    "c": 4,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Economics - Module 2 (Macroeconomics)",
    "c": 7,
    "y": 2,
    "k": "g",
    "m": "ECONOMICS"
   },
   {
    "n": "Statistics",
    "c": 8,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Critical Approaches to the Arts - II - Module 1",
    "c": 6,
    "y": 2,
    "k": "g",
    "m": "ARTS"
   },
   {
    "n": "Financial Accounting - Module 1",
    "c": 5,
    "y": 2,
    "k": "g",
    "m": "ACCOUNTING"
   },
   {
    "n": "Cultural Anthropology",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Financial Accounting - Module 2",
    "c": 5,
    "y": 2,
    "k": "g",
    "m": "ACCOUNTING"
   },
   {
    "n": "Fundamentals of Organization",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Critical Approaches to the Arts - II - Module 2",
    "c": 6,
    "y": 2,
    "k": "g",
    "m": "ARTS"
   },
   {
    "n": "Law - Module 2 (Comparative Public Law)",
    "c": 6,
    "y": 2,
    "k": "g",
    "m": "LAW"
   },
   {
    "n": "Second foreign language",
    "c": 4,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Leadership and Managerial Skills Seminar",
    "c": 2,
    "y": 2,
    "k": "p"
   },
   {
    "n": "Business Planning and Control",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Management of public and not for profit organizations",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Advanced Management - Module 1 (Competitive strategies in creative industries)",
    "c": 7,
    "y": 3,
    "k": "g",
    "m": "ADVANCED MANAGEMENT"
   },
   {
    "n": "Advanced Management - Module 2 (Marketing in creative industries)",
    "c": 8,
    "y": 3,
    "k": "g",
    "m": "ADVANCED MANAGEMENT"
   },
   {
    "n": "Company and Business Law",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Finance - Module 1 (Corporate Finance)",
    "c": 5,
    "y": 3,
    "k": "g",
    "m": "FINANCE"
   },
   {
    "n": "Finance - Module 2 (Financial Markets and Institutions)",
    "c": 5,
    "y": 3,
    "k": "g",
    "m": "FINANCE"
   },
   {
    "n": "Public Finance",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "#1",
    "c": 6,
    "y": 3,
    "k": "s"
   }
  ],
  "BIG": [
   {
    "n": "Political science and comparative politics",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Quantitative methods for social sciences - Module 1 (Mathematics)",
    "c": 6,
    "y": 1,
    "k": "g",
    "m": "Quantitative methods for social sciences"
   },
   {
    "n": "Law - Module 1 (Comparative public law)",
    "c": 6,
    "y": 1,
    "k": "g",
    "m": "Law"
   },
   {
    "n": "Introduction to economics - Module 1 (Microeconomics)",
    "c": 8,
    "y": 1,
    "k": "g",
    "m": "Introduction to economics"
   },
   {
    "n": "Introduction to economics - Module 2 (Macroeconomics)",
    "c": 6,
    "y": 1,
    "k": "g",
    "m": "Introduction to economics"
   },
   {
    "n": "Political philosophy",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Quantitative methods for social sciences - Module 2 (Statistics)",
    "c": 6,
    "y": 1,
    "k": "g",
    "m": "Quantitative methods for social sciences"
   },
   {
    "n": "Marketing research skills for public policy",
    "c": 3,
    "y": 1,
    "k": "p"
   },
   {
    "n": "Computer science",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Prima lingua",
    "c": 5,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Management of government organizations",
    "c": 8,
    "y": 2,
    "k": "g"
   },
   {
    "n": "International relations",
    "c": 8,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Public economics",
    "c": 8,
    "y": 2,
    "k": "g"
   },
   {
    "n": "History - Module 1 (Global history)",
    "c": 6,
    "y": 2,
    "k": "g",
    "m": "History"
   },
   {
    "n": "Negotiation skills",
    "c": 3,
    "y": 2,
    "k": "p"
   },
   {
    "n": "Policy evaluation",
    "c": 8,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Economics and politics of the European Union",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Law - Module 2 (International and European law)",
    "c": 6,
    "y": 2,
    "k": "g",
    "m": "Law"
   },
   {
    "n": "Political economics",
    "c": 8,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Seconda lingua",
    "c": 5,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Sociology",
    "c": 7,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Public governance",
    "c": 8,
    "y": 3,
    "k": "g"
   },
   {
    "n": "#1",
    "c": 6,
    "y": 3,
    "k": "o"
   },
   {
    "n": "#2",
    "c": 6,
    "y": 3,
    "k": "o"
   },
   {
    "n": "History - Module 2 (History of political institutions)",
    "c": 6,
    "y": 3,
    "k": "g",
    "m": "History"
   },
   {
    "n": "Media, political elites and the public",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "#3",
    "c": 6,
    "y": 3,
    "k": "o"
   },
   {
    "n": "#4",
    "c": 6,
    "y": 3,
    "k": "s"
   }
  ]
 },
 "master": {
  "CRSG": [
   {
    "n": "Emerging topics in cybersecurity (Politecnico)",
    "c": 2,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Software methodologies and architectures for security Module II: Software Engineering Methodologies for Security",
    "c": 6,
    "y": 1,
    "k": "g",
    "m": "Software Methodologies and Architectures for Security"
   },
   {
    "n": "Software Methodologies and Architectures for Security Module I: Enterprise Ict Architectures",
    "c": 6,
    "y": 1,
    "k": "g",
    "m": "Software Methodologies and Architectures for Security"
   },
   {
    "n": "Artificial Intelligence for Security",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Cyber Risk and Data Protection Law",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Emerging topics in cybersecurity (at Bocconi)",
    "c": 2,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Technology Risk Governance",
    "c": 5,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Methods and Data Analytics for Risk Assessment",
    "c": 7,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Cyber Security Technologies Procedures and Policies",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Institutional Scenarios of Cyber Risk",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Strategy and Governance for Cyber Risk",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "#1",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "Behavioural Skills Seminar (second semester Bocconi)",
    "c": 2,
    "y": 2,
    "k": "p"
   },
   {
    "n": "#2",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "EU Language",
    "c": 4,
    "y": 2,
    "k": "g"
   },
   {
    "n": "#3",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "#4",
    "c": 8,
    "y": 2,
    "k": "i"
   },
   {
    "n": "Ethics Seminar (first semester Politecnico)",
    "c": 2,
    "y": 2,
    "k": "p"
   },
   {
    "n": "#5",
    "c": 6,
    "y": 2,
    "k": "o"
   }
  ],
  "AI": [
   {
    "n": "AI ethics seminar",
    "c": 2,
    "y": 1,
    "k": "p"
   },
   {
    "n": "Information theory",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Algorithms for optimization and inference",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Machine learning Lab",
    "c": 2,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Computer vision and image processing",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Deep Learning and Reinforcement Learning",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Software engineering",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Language technology",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Mathematical Methods in Computer Science or Analysis of algorithms and data structures",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "#1",
    "c": 8,
    "y": 2,
    "k": "i"
   },
   {
    "n": "#2",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "Open choice course from Bocconi list",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "1 out of a short list* from Bocconi list:",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Foreign language",
    "c": 4,
    "y": 2,
    "k": "g"
   },
   {
    "n": "#3",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "#4",
    "c": 6,
    "y": 2,
    "k": "o"
   }
  ],
  "GIO": [
   {
    "n": "Economics and policy of global markets",
    "c": 9,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Quantitative methods for social sciences",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Policy analysis and evaluation",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "National and international institutions law6Politics and policy making",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Strategic and HR management in public organizations",
    "c": 9,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Politics and policy making",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Government and international organizations: trends and careers",
    "c": 3,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Major compulsory course",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Public accounting and performance management",
    "c": 9,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Enhancing Experience Curricular Supplementary Activities",
    "c": 2,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Professional English seminars (lessons + exam)",
    "c": 2,
    "y": 2,
    "k": "p"
   },
   {
    "n": "#1",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "#2",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "#3",
    "c": 8,
    "y": 2,
    "k": "i"
   },
   {
    "n": "Second language (lessons + exam 1st semester)",
    "c": 4,
    "y": 2,
    "k": "g"
   },
   {
    "n": "#4",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "#5",
    "c": 6,
    "y": 2,
    "k": "o"
   }
  ],
  "IM-GLOBAL": [
   {
    "n": "Performance evaluation and measurement",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Global scenarios, Module 2 (Macroeconomics)",
    "c": 6,
    "y": 1,
    "k": "g",
    "m": "Global scenarios"
   },
   {
    "n": "Principles of business analytics",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Seminar on collaborative competences",
    "c": 2,
    "y": 1,
    "k": "p"
   },
   {
    "n": "Global scenarios, Module 1 (Geopolitics and business)",
    "c": 6,
    "y": 1,
    "k": "g",
    "m": "Global scenarios"
   },
   {
    "n": "Business Game",
    "c": 2,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Managing Organizations",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "International finance",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Marketing Analytics",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Comparative Corporate Law",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Global Strategy",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "#1",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "#2",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "Global operations and supply chain management",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "#3",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "Professional English seminars (lessons + exam)",
    "c": 2,
    "y": 2,
    "k": "p"
   },
   {
    "n": "Second foreign language (lessons + exam 1st semester 2nd year)",
    "c": 4,
    "y": 2,
    "k": "g"
   }
  ],
  "FINANCE": [
   {
    "n": "Empirical Finance",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Theory of finance",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Financial Data Science",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Financial institutions and market law",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Financial reporting and Analysis Lab",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Risk management and value in banking and insurance",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Corporate finance (Business valuation)",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Investment banking",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Quantitative finance and derivatives - Module 2",
    "c": 6,
    "y": 1,
    "k": "g",
    "m": "Quantitative finance and derivatives"
   },
   {
    "n": "Behavioural skill seminar - Public Speaking",
    "c": 2,
    "y": 1,
    "k": "p"
   },
   {
    "n": "Quantitative finance and derivatives - Module 1",
    "c": 6,
    "y": 1,
    "k": "g",
    "m": "Quantitative finance and derivatives"
   },
   {
    "n": "Professional English seminars (lessons + exam)",
    "c": 2,
    "y": 2,
    "k": "p"
   },
   {
    "n": "#1",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "#2",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "Second foreign language",
    "c": 4,
    "y": 2,
    "k": "g"
   },
   {
    "n": "#3",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "#4",
    "c": 6,
    "y": 2,
    "k": "o"
   }
  ],
  "IM": [
   {
    "n": "Global strategy",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Global scenarios Module 2 (Macroeconomics)",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Global operations and supply chain management",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Performance measurement",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Marketing analytics",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "International finance",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Global scenarios Module 1 (Geopolitics and business)",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "International comparative I business law",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Managing organizations",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Principles of business analytics",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Second foreign language",
    "c": 4,
    "y": 2,
    "k": "g"
   },
   {
    "n": "#1",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "#2",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "#3",
    "c": 6,
    "y": 2,
    "k": "o"
   }
  ],
  "DAAIHS": [
   {
    "n": "Data Systems in healthcare (@ Bocconi)",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Privacy ethics and regulations in the application of AI seminar (@ Bocconi)",
    "c": 2,
    "y": 1,
    "k": "p"
   },
   {
    "n": "Machine Learning (@ Bocconi)",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Advanced computer programming (@ Bocconi)",
    "c": 9,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Artificial Intelligence module 2 (@ Bocconi)",
    "c": 6,
    "y": 1,
    "k": "g",
    "m": "Artificial Intelligence"
   },
   {
    "n": "Biology and genetics (@ Humanitas)",
    "c": 4,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Data Science for Clinics (@ Humanitas)",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Clinical Epidemiology (@ Humanitas)",
    "c": 10,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Artificial Intelligence module 1 (@ Bocconi)",
    "c": 6,
    "y": 1,
    "k": "g",
    "m": "Artificial Intelligence"
   },
   {
    "n": "Advanced statistics for health sciences (@ Bocconi)",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "#1",
    "c": 6,
    "y": 1,
    "k": "o"
   },
   {
    "n": "#2",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "#3",
    "c": 6,
    "y": 2,
    "k": "i"
   },
   {
    "n": "Applications of artificial intelligence in health sciences (@ Humanitas)",
    "c": 10,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Guidelines for quality assessment and reporting in AI publication seminar (@ Humanitas)",
    "c": 2,
    "y": 2,
    "k": "p"
   },
   {
    "n": "Foreign language (1st sem) (@ Humanitas)",
    "c": 2,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Next generation sequencing and bioinformatics (@ Humanitas)",
    "c": 7,
    "y": 2,
    "k": "g"
   }
  ],
  "DSBA": [
   {
    "n": "Behavioral skills seminar",
    "c": 2,
    "y": 1,
    "k": "p"
   },
   {
    "n": "Business Analytics",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Computer Programming and Database Systems",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Natural Language Processing",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Statistics and Probability",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Machine Learning",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Econometrics for Big Data",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "#1",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "Digital Privacy Seminar",
    "c": 2,
    "y": 2,
    "k": "p"
   },
   {
    "n": "#2",
    "c": 8,
    "y": 2,
    "k": "i"
   },
   {
    "n": "#3",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "Foreign language",
    "c": 4,
    "y": 2,
    "k": "g"
   }
  ],
  "MM": [
   {
    "n": "Market research and business forecasting",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Understanding consumer (Consumer behavior and CCT) Module 1",
    "c": 5,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Industry analysis (Industrial economics and economics of innovation)",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Brand management",
    "c": 5,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Understanding consumer (Consumer behavior and CCT) Module 2",
    "c": 5,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Channel marketing (Trade evolution analysis and planning)",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Legal issues in marketing",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Strategic marketing and analytics (Data & analytics for strategic marketing decisions) Module 1",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Behavioural skills seminars",
    "c": 2,
    "y": 1,
    "k": "p"
   },
   {
    "n": "Innovation in the data economy",
    "c": 5,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Strategic marketing and analytics (Web analytics) Module 2",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "#1",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "#2",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "Enhancing Experience Curricular Supplementary Activities",
    "c": 2,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Professional English seminars (lessons + exam)",
    "c": 2,
    "y": 2,
    "k": "p"
   },
   {
    "n": "#3",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "#4",
    "c": 8,
    "y": 2,
    "k": "i"
   },
   {
    "n": "Second foreign language (lessons + exam 1st semester 2nd year)",
    "c": 4,
    "y": 2,
    "k": "g"
   },
   {
    "n": "#5",
    "c": 6,
    "y": 2,
    "k": "o"
   }
  ],
  "IM-CONCENTRATION": [
   {
    "n": "1 course to be chosen",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Corporate strategy",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Marketing management – advanced",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Business Game",
    "c": 2,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Advanced corporate finance for management",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Performance measurement",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Behaviourial skills seminars",
    "c": 2,
    "y": 1,
    "k": "p"
   },
   {
    "n": "Economy and Society – module 1",
    "c": 6,
    "y": 1,
    "k": "g",
    "m": "Economy and Society"
   },
   {
    "n": "Economy and Society – module 2",
    "c": 6,
    "y": 1,
    "k": "g",
    "m": "Economy and Society"
   },
   {
    "n": "Principles of business analytics",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Human resources management",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "#1",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "Second foreign language (lessons + exam 1st semester 2nd year)",
    "c": 4,
    "y": 2,
    "k": "g"
   },
   {
    "n": "#2",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "1 compulsory concentration course",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Professional English seminars (lessons + exam)",
    "c": 2,
    "y": 2,
    "k": "p"
   },
   {
    "n": "1 concentration elective on data analysis",
    "c": 6,
    "y": 2,
    "k": "g"
   }
  ],
  "AFM": [
   {
    "n": "Corporate Reporting – Module 1 Corporate financial reporting",
    "c": 8,
    "y": 1,
    "k": "g",
    "m": "Corporate Reporting"
   },
   {
    "n": "Fair value accounting reporting and valuation",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Macroeconomic trends for Business decisions",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Behavioural skills seminars",
    "c": 2,
    "y": 1,
    "k": "p"
   },
   {
    "n": "Corporate Reporting – Module 2 Non financial and sustainability reporting",
    "c": 6,
    "y": 1,
    "k": "g",
    "m": "Corporate Reporting"
   },
   {
    "n": "Performance measurement and control systems",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Data analysis for business decisions",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Business law (selected corporate and tax issues in management and internal auditing) or Corporate Global Tax Strategies",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Financial management and financial markets",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Corporate governance",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "#1",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "Professional English seminars (lessons + exam)",
    "c": 2,
    "y": 2,
    "k": "p"
   },
   {
    "n": "#2",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "#3",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "Enhancing Experience Curricular Supplementary Activities",
    "c": 2,
    "y": 2,
    "k": "g"
   },
   {
    "n": "#4",
    "c": 6,
    "y": 2,
    "k": "i"
   },
   {
    "n": "Second language (lessons + exam 1st semester 2nd year)",
    "c": 4,
    "y": 2,
    "k": "g"
   },
   {
    "n": "#5",
    "c": 6,
    "y": 2,
    "k": "o"
   }
  ],
  "CLELI": [
   {
    "n": "Tassazione delle società e dei gruppi",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Modelli finanziari per la valutazione",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Finanza strategica",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Analisi Strategiche e valutazioni finanziarie",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Sistemni di corporate governance",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Principi contabili internazionali",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Seiminari per lo sviluppo di abilità comportamentali",
    "c": 2,
    "y": 1,
    "k": "p"
   },
   {
    "n": "Bilancio e operazioni di gestione straordinaria",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Diritto commerciale (corso progredito)",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "#1",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "#2",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "lingua 2 (didattica + esame I sem 2° anno)",
    "c": 4,
    "y": 2,
    "k": "g"
   },
   {
    "n": "#3",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "Professional English seminars (lessons + exam)",
    "c": 2,
    "y": 2,
    "k": "p"
   },
   {
    "n": "Diritto dei mercati e degli strumenti finanziari",
    "c": 6,
    "y": 2,
    "k": "g"
   }
  ],
  "ESS": [
   {
    "n": "Advanced statistics for economics and social sciences",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Econometrics",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Foundations of social sciences module I (Empirical research methods and data analysis)",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "#1",
    "c": 6,
    "y": 1,
    "k": "o"
   },
   {
    "n": "Competition Law and Practice",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "#2",
    "c": 6,
    "y": 1,
    "k": "o"
   },
   {
    "n": "Behavioural skills seminars",
    "c": 2,
    "y": 1,
    "k": "p"
   },
   {
    "n": "Advanced mathematics for economics and social sciences",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "#3",
    "c": 6,
    "y": 1,
    "k": "o"
   },
   {
    "n": "1 compulsory course to be chosen from",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "#4",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "#5",
    "c": 8,
    "y": 2,
    "k": "i"
   },
   {
    "n": "#6",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "Enhancing Experience Curricular Supplementary Activities",
    "c": 2,
    "y": 2,
    "k": "g"
   },
   {
    "n": "#7",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "#8",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "Professional English seminars (lessons + exam)",
    "c": 2,
    "y": 2,
    "k": "p"
   },
   {
    "n": "Second foreign language (lessons + exam 1st semester 2nd year)",
    "c": 4,
    "y": 2,
    "k": "g"
   }
  ],
  "PPA": [
   {
    "n": "Population dynamics and policies",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Political science Module 2 (International relations and politics)",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Political science Module 1 (Topics in comparative politics)",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Methods and tools for policy analysis",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Behavioral Skills Seminar",
    "c": 2,
    "y": 1,
    "k": "p"
   },
   {
    "n": "Public administration",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Public economics",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Economics and politics",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Decisions and organizations",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Law and policy making",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "#1",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "#2",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "Second foreign language",
    "c": 4,
    "y": 2,
    "k": "g"
   },
   {
    "n": "#3",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "#4",
    "c": 6,
    "y": 2,
    "k": "o"
   }
  ],
  "TS": [
   {
    "n": "Sustainable Finance and ESG Investing",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Critical Thinking and Complex Decision Making seminar",
    "c": 2,
    "y": 1,
    "k": "p"
   },
   {
    "n": "Materials Towards Circular Economy",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Designing Sustainable Cities",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Impact and Sustainability Measurement",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Innovation for Sustainability",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Technologies for Energy and Sustainable Transition module 2 (Technologies for the Energy Transition Towards Sustainability)",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Sustainable Leadership seminar",
    "c": 2,
    "y": 1,
    "k": "p"
   },
   {
    "n": "Management and Economics for Sustainability module 1(Corporate Sustainability Strategies and Governance)",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Technologies for Energy and Sustainable Transition module 1 (Ecological Processes Environmental Impacts and Transition Towards Sustainability)",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "ESG Law",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Management and Economics for Sustainability module 2 (Environmental Economics and Climate Change)",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Business and Marketing Plan Workshop 1st sem.",
    "c": 3,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Data Analytics for Sustainability 1st sem.",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "#1",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "Sustainable Operations & Supply Chain Management 2nd sem",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Foreign language (lessons and exam) 1st sem",
    "c": 4,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Sustainable Entrepreneurship Workshop 2nd sem.",
    "c": 3,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Diversity and Global Policy 1st sem. | Technologies and Systems for Sustainable Mobility 2nd sem",
    "c": 6,
    "y": 2,
    "k": "g"
   }
  ],
  "ACME": [
   {
    "n": "Quantitative methods for management",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Applied research in cultural industries and institutions : module II (marketing and crm in the arts)",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Behavioural skills seminars",
    "c": 2,
    "y": 1,
    "k": "p"
   },
   {
    "n": "Cultural mediation",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Major’s workshop 1",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Project and team management",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Performance measurement",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Management of cultural industries and institutions module I (strategy and governance)",
    "c": 6,
    "y": 1,
    "k": "g",
    "m": "Management of cultural industries and institutions"
   },
   {
    "n": "Management of cultural industries and institutions module II (comparative cultural public policies and fundraising)",
    "c": 6,
    "y": 1,
    "k": "g",
    "m": "Management of cultural industries and institutions"
   },
   {
    "n": "European and international advanced IP law",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Major’s workshop 2",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Professional English seminars (lessons + exam)",
    "c": 2,
    "y": 2,
    "k": "p"
   },
   {
    "n": "Major’s workshop 3",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "#1",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "#2",
    "c": 8,
    "y": 2,
    "k": "i"
   },
   {
    "n": "Major’s workshop 4",
    "c": 6,
    "y": 2,
    "k": "g"
   },
   {
    "n": "#3",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "Enhancing Experience Curricular Supplementary Activities",
    "c": 2,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Second foreign language (lessons + exam 1st semester 2nd year)",
    "c": 4,
    "y": 2,
    "k": "g"
   }
  ],
  "EMIT": [
   {
    "n": "Data analytics and visualization",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Technology and innovation strategy",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Business Economics II (Analytic Methods)",
    "c": 8,
    "y": 1,
    "k": "g",
    "m": "Business Economics"
   },
   {
    "n": "Business Economics I (Empirical Methods)",
    "c": 8,
    "y": 1,
    "k": "g",
    "m": "Business Economics"
   },
   {
    "n": "Strategic decision making",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Behavioural skills seminars",
    "c": 2,
    "y": 1,
    "k": "p"
   },
   {
    "n": "Venture capital and valuation",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "1 major compulsory course",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Intellectual property and competition law",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Fundamentals of innovation and industrial change",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "#1",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "Enhancing Experience Curricular Supplementary Activities",
    "c": 2,
    "y": 2,
    "k": "g"
   },
   {
    "n": "#2",
    "c": 8,
    "y": 2,
    "k": "i"
   },
   {
    "n": "#3",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "#4",
    "c": 6,
    "y": 2,
    "k": "o"
   },
   {
    "n": "Professional English seminars (lessons + exam)",
    "c": 2,
    "y": 2,
    "k": "p"
   },
   {
    "n": "Second language (lessons + exam 1st semester 2nd year)",
    "c": 4,
    "y": 2,
    "k": "g"
   },
   {
    "n": "1 Innovation Specific Elective**",
    "c": 6,
    "y": 2,
    "k": "g"
   }
  ]
 },
 "clmg": {
  "CLMG": [
   {
    "n": "Istituzioni di diritto privato- modulo 1",
    "c": 8,
    "y": 1,
    "k": "g",
    "m": "Istituzioni di diritto privato"
   },
   {
    "n": "Filosofia del diritto",
    "c": 8,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Inglese (I lingua) (didattica ed esame)",
    "c": 4,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Diritto costituzionale italiano ed europeo",
    "c": 10,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Principi di economia a scelta: Economia/Scienze delle finanze",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Critical thinking",
    "c": 1,
    "y": 1,
    "k": "p"
   },
   {
    "n": "Istituzioni di diritto privato- modulo 2",
    "c": 6,
    "y": 1,
    "k": "g",
    "m": "Istituzioni di diritto privato"
   },
   {
    "n": "Diritto romano - modulo 1",
    "c": 8,
    "y": 1,
    "k": "g",
    "m": "Diritto romano"
   },
   {
    "n": "Quantitative methods",
    "c": 6,
    "y": 1,
    "k": "g"
   },
   {
    "n": "Economia aziendale e bilancio - modulo 1",
    "c": 6,
    "y": 2,
    "k": "g",
    "m": "Aziendale"
   },
   {
    "n": "Management and Accounting - Module 2 (Accounting and Financial Statement Analysis)",
    "c": 6,
    "y": 2,
    "k": "g",
    "m": "Aziendale"
   },
   {
    "n": "Diritto commerciale",
    "c": 10,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Legal argumentation and economic analysis of law",
    "c": 8,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Informatica per giurisprudenza",
    "c": 3,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Legal English",
    "c": 3,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Diritto comparato a scelta: Private law/ Diritto pubblico",
    "c": 9,
    "y": 2,
    "k": "g"
   },
   {
    "n": "Roman law - Module 2 (Roman Foundations of European Law)",
    "c": 6,
    "y": 2,
    "k": "g",
    "m": "Diritto romano"
   },
   {
    "n": "History of law - Module 1 (Introduction to European Legal History)",
    "c": 6,
    "y": 2,
    "k": "g",
    "m": "History of law"
   },
   {
    "n": "Storia del diritto - Modulo 2",
    "c": 8,
    "y": 2,
    "k": "g",
    "m": "History of law"
   },
   {
    "n": "Diritto contabile e fiscale - modulo 1",
    "c": 5,
    "y": 3,
    "k": "g",
    "m": "Diritto contabile e fiscale"
   },
   {
    "n": "Diritto penale",
    "c": 10,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Diritto processuale civile - modulo 2",
    "c": 6,
    "y": 3,
    "k": "g",
    "m": "Diritto processuale civile"
   },
   {
    "n": "Seconda lingua straniera (didattica ed esame)",
    "c": 4,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Diritto processuale penale",
    "c": 8,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Diritto contabile e fiscale - modulo 2",
    "c": 7,
    "y": 3,
    "k": "g",
    "m": "Diritto contabile e fiscale"
   },
   {
    "n": "EU law",
    "c": 9,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Diritto del lavoro",
    "c": 6,
    "y": 3,
    "k": "g"
   },
   {
    "n": "Diritto processuale civile - modulo 1",
    "c": 8,
    "y": 3,
    "k": "g",
    "m": "Diritto processuale civile"
   },
   {
    "n": "Diritto del lavoro (corso progredito) a scelta fra: Casi di diritto del lavoro, Istituzioni del mercato del lavoro, European social law",
    "c": 6,
    "y": 4,
    "k": "g"
   },
   {
    "n": "Diritto amministrativo a scelta fra: Diritto amministrativo, Diritto amministrativo italiano ed europeo",
    "c": 10,
    "y": 4,
    "k": "g"
   },
   {
    "n": "Diritto civile a scelta fra: Contratti e obbligazioni, European and International contracts",
    "c": 8,
    "y": 4,
    "k": "g"
   },
   {
    "n": "International law",
    "c": 9,
    "y": 4,
    "k": "g"
   },
   {
    "n": "Diritto commerciale (corso progredito) a scelta fra: Casi e questioni di diritto societario, Operazioni straordinarie, Antitrust law",
    "c": 6,
    "y": 4,
    "k": "g"
   },
   {
    "n": "Diritto processuale penale (corso progredito) a scelta fra: Diritto dell'esecuzione penale, Processo penale agli enti, Procedura penale europea",
    "c": 6,
    "y": 4,
    "k": "g"
   },
   {
    "n": "Diritto costituzionale (corso progredito) a scelta fra: Giustizia costituzionale, Diritto pubblico dell'economia, Transnational constitutional law and government policies",
    "c": 8,
    "y": 4,
    "k": "g"
   },
   {
    "n": "Diritto penale (corso progredito) a scelta fra: Parte speciale del codice penale, Focus su criminalità economica, Paths of internationalization",
    "c": 6,
    "y": 4,
    "k": "g"
   },
   {
    "n": "Diritto amministrativo (corso progredito) a scelta fra: Diritto processuale amministrativo, Environmental law. Global Administrative Law",
    "c": 8,
    "y": 5,
    "k": "g"
   },
   {
    "n": "Seminari / Moot / Cliniche legali / opzionale n4",
    "c": 6,
    "y": 5,
    "k": "g"
   },
   {
    "n": "Diritto civile (corso progredito) a scelta fra: Diritto Bancario, Diritto Finanziario, Diritto Assicurativo",
    "c": 8,
    "y": 5,
    "k": "g"
   },
   {
    "n": "#1",
    "c": 6,
    "y": 5,
    "k": "o"
   },
   {
    "n": "#2",
    "c": 6,
    "y": 5,
    "k": "o"
   },
   {
    "n": "Computing AI and the Law",
    "c": 4,
    "y": 5,
    "k": "g"
   },
   {
    "n": "#3",
    "c": 6,
    "y": 5,
    "k": "s"
   }
  ]
 }
};
